### ISSUE TITLE
Use backup host `lt -h "http://serverless.social" -p PORT` if site is down

### ISSUE THREAD

**Issue by aakashapoorv** [localtunnel/localtunnel#344]
Use `lt -h "http://serverless.social" -p PORT`

**Comment by adanfrancisco** [comment]
Thank you!!!

**Comment by outkaj** [comment]
for me, this command works, but the program crashes pretty frequently, needing a restart. Is this happening to anyone else?

**Comment by catsica69** [comment]
thanks @aakashapoorv its working

**Comment by aakashapoorv** [comment]
@outkaj I changed dns yesterday, dns propagation usually take sometime. Let me know if you still have the issue

**Comment by zinig** [comment]
Thank you!!! but the url changes every run even if used --subdomain
es.
lt -h "http://serverless.social" -p 5000 --subdomain mySubDomain

**Comment by imlookerkid** [comment]
@aakashapoorv its working, thanks

**Comment by aaronjanse** [comment]
> Thank you!!! but the url changes every run even if used --subdomain
@zinig I just checked, and fixed subdomains seem to work now!

Tysm @aakashapoorv! You're a hero!

**Comment by Axist** [comment]
https doesn't work with serverless.social tho

**Comment by besoeasy** [comment]
what of code you are running, it doesn't support --subdomain, doesn't work with https,  then how can it be used as alternative ?

**Comment by catsica69** [comment]
@besoeasy you moron, its a free service. take it or leave it. pipe down your mouth and stop trolling on github you dumb firetruck. you are will be reported for trolling

**Comment by catsica69** [comment]
@besoeasy `Aman Singh Katal` after some digging i realised you have created alot of fake users on `Mar 18 2018` 
@mhenlndeij @manecaomjj @conehbfcop @afopmnbncf @hehfbnikmc @user234324324 @hmelhhioaj @gpbmjjeiam @opfjleoplm @lgigflaif and a-lot more who are just following you

you are calming that you are Millionaire by 17 and yet looking for free service buying doamins form namecheap and hosting sites on fastly taking pictures near other people's car not in Jandor Hukmi.

lets report all @besoeasy

**Comment by ayunami2000** [comment]
@catsica69 no u dumb firetruck

**Comment by brookmg** [comment]
> https doesn't work with serverless.social tho

Any idea how to enable it?

**Comment by ravtakhar** [comment]
Looks like this command is not working today.

**Comment by hayashi-ay** [comment]
Same here!

**Comment by aakashapoorv** [comment]
@ravtakhar @hayashi-ay fixed, follow server status here `https://discord.gg/WHBS3uX`

**Comment by vinc01100101** [comment]
Thanks for this!!

**Comment by hayashi-ay** [comment]
The `--subdomin` option seems not working today, here is the output:

```
lt -h "http://serverless.social" -p 8081 --subdomain 'hayashis-kitchen'
your url is: http://bitter-snail-38.serverless.social
```

**Comment by aakashapoorv** [comment]
@hayashi-ay looks like `hayashis-kitchen` is already taken, I've restarted the server. It should work now

**Comment by Lechuck3** [comment]
Hi, today i start to use your server and it works for a few time, it seems down right now. i use to acces to my raspberry pi apache server over gc-nat.

**Comment by Lechuck3** [comment]
sorry
 lt -h "http://serverless.social" -p 80 --subdomain bellvis 
or
 lt -h "http://serverless.social" -p 80

**Comment by aakashapoorv** [comment]
@Lechuck3 fixed, follow server status here https://discord.gg/WHBS3uX

**Comment by Lechuck3** [comment]
Fine! Thanks!

**Comment by avivtsadik** [comment]
i have wrote 
lt -h https://discord.gg/WHBS3uX --port 5050 --subdomain avivqq
and it says:
your url is: undefined 
i also tried
lt -h http://serverles.social --port 5050 --subdomain avivqq
and it doesnt work
it is weird because an hour ago this: http://serverles.social  worked...

**Comment by ayunami2000** [comment]
Click the discord link to see the server status. Also your second command
has a typo in the url, you put "serverles" instead of "serverless"

**Comment by dcsan** [comment]
@aakashapoorv thanks for setting this up. 
I have a server with domains too, perhaps you could publish the info on how you set this up, so other people could do it too? Like a distributed localTunnel !

**Comment by aakashapoorv** [comment]
@dcsan `https://github.com/localtunnel/server`

**Comment by ardyfeb** [comment]
got 404 every request

**Comment by dcsan** [comment]
localtunnel appears to be down, slammed by WFH people. you can setup your own server tho, see the note above from aakashapoorv

**Comment by aakashapoorv** [comment]
fixed, follow server status here `https://discord.gg/WHBS3uX`

**Comment by m1guelpf** [comment]
Hey @aakashapoorv, that Discord invite expired, any chance of getting a new one?

**Comment by aakashapoorv** [comment]
@m1guelpf looking above link is working. I generate one more link `https://discord.gg/3XFh2Y` try this

**Comment by m1guelpf** [comment]
@aakashapoorv 
<img width="497" alt="Screenshot 2020-04-15 at 21 17 23" src="https://user-images.githubusercontent.com/23558090/79379024-87c96e80-7f5e-11ea-9e6a-99cd9a5c0528.png">

**Comment by GeorgiosGoniotakis** [comment]
Hello, @aakashapoorv I just tested this and works fine. Would you mind sharing with us more information about the URL? Is it a service that you provide? How did you set it up? The open-source community would potentially be interested in contributing in different ways. Thanks 😄

**Comment by aakashapoorv** [comment]
@m1guelpf try clicking this link https://discord.gg/3XFh2Y or add me in Discord `Aakash#4144`

**Comment by aakashapoorv** [comment]
@GeorgiosGoniotakis using `https://github.com/serverless-social/server` which is a straight fork from localtunnel's server for now. We are planning to improve it and add new features and analytics, development will start soon. check `#development` channel `https://discord.gg/3XFh2Y`

**Comment by cesarochoa2006** [comment]
Thanks a lot. it worked for me

**Comment by robertoandrade** [comment]
@aakashapoorv having issues connecting to serverless.social via https since the SSL cert chain seems to be broken according to https://www.ssllabs.com/ssltest/analyze.html?d=serverless.social

When I try:

```
curl -v https://serverless.social
* Rebuilt URL to: https://serverless.social/
*   Trying 3.20.243.36...
* TCP_NODELAY set
* Connected to serverless.social (3.20.243.36) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* stopped the pause stream!
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Or any subdomain, it seems the wildcard cert being used doesn't include the intermediate CA from Let's Encrypt and causes all software that tries to validate the cert to fail.

Would you be able to address that server side so we don't have to muck with ignoring SSL certification on all clients that try to use the URLs?

**Comment by AnjneyaP** [comment]
https://serverless.social is crashing too frequently.. Localtunnel was awesome . use ngrok.. its more secure

**Comment by digitalmio** [comment]
@aakashapoorv can you tell me from your experience how much CPU/memory localtunnel requires? I might be able to help with alternative server as well, just need to know what kind of load to expect... Thanks

**Comment by robertoandrade** [comment]
Seems to be down for a few days now

**Comment by marvinahv** [comment]
Not working for me

**Comment by aakashapoorv** [comment]
@digitalmio CPU consumption is very low and memory about 1 gb is good, only bandwidth is high. I'm using small ec2 instance

**Comment by aakashapoorv** [comment]
@digitalmio join `https://discord.gg/WHBS3uX` and contact me in dev channel if you want to manage a server

**Comment by aakashapoorv** [comment]
@robertoandrade @marvinahv domain is up now. Join `https://discord.gg/WHBS3uX` for updates

**Comment by aakashapoorv** [comment]
I have also renewed SSL certificate so `lt -h "https://serverless.social" -p PORT` will work now. SSL is also enabled on subdomains.

**Comment by aakashapoorv** [comment]
@robertoandrade cert chain is fixed `https://www.ssllabs.com/ssltest/analyze.html?d=serverless.social`

**Comment by przano** [comment]
> I have also renewed SSL certificate so `lt -h "https://serverless.social" -p PORT` will work now. SSL is also enabled on subdomains.

I tried    `lt -h "https://serverless.social" -p 2020`  , but it just hangs there and does nothing. I must be doing something wrong

**Comment by aakashapoorv** [comment]
@przano it's working for me

**Comment by przano** [comment]
@aakashapoorv thanks for confirmation. Unfortunately, still not working for me. If this information helps, I am trying to run this on a Raspberry Pi via terminal window. When I run, it just hangs there. I would expect something like "your url is https://randomstring.serverless.social, nothing happens. I just ctrl-C to kill it.

**Comment by przano** [comment]
@aakashapoorv I tried again this morning, still didn't work. However, I just tried it again (a few hours later) and it works now. Weird.

**Comment by PMATTT** [comment]
06/13/2020 =>The service doesn't work.
(lt -h "http://serverless.social" -p 3000)

**Comment by aakashapoorv** [comment]
@przano @PMATTT check server status here `https://discord.gg/WHBS3uX`.

**Comment by 3b7ameed** [comment]
Thanks mate

**Comment by zquall** [comment]
Is working for me. Thank you Guys!
lt -p #### -s XXXX -h "http://serverless.social"
#### = your port
XXXX = your custom subdomain

**Comment by TheBoroer** [comment]
I am now hosting localtunnel.me for this project so it should work like before. The only difference is that I'm handing out subdomains under the domain `*.loca.lt` instead of `*.localtunnel.me` (that's because I don't have full DNS control and without it can't get a free wildcard cert for the domain without). Let me know if you run into any issues. Feel free to use either serverless.social or localtunnel.me.  I'm also in the serverless discord group :)

**Comment by Rajashekar231990** [comment]
lt -h "https://serverless.social" -p 8080 

not working...

**Comment by felipemarques** [comment]
not working
