### ISSUE TITLE
Crashing after a few minutes

### ISSUE THREAD

**Issue by dpkonofa** [localtunnel/localtunnel#81]
```
events.js:85
       throw er; // Unhandled 'error' event
            ^
Error: connection refused: localtunnel.me:37302 (check your firewall settings)
    at Socket.<anonymous> (/usr/local/lib/node_modules/localtunnel/lib/TunnelCluster.js:45:32)
    at Socket.emit (events.js:107:17)
    at net.js:451:14
    at process._tickCallback (node.js:355:11)
```

I keep getting this error repeatedly on multiple instances of localtunnel but I can't really pin down what's causing it.  I can't imagine that the connection is actually getting refused because the tunnel starts up and works normally for however many minutes until it decides to stop working.  Is there any way to get it to retry instead of just crashing and closing the tunnel?  Right now this is making it really unreliable to use localtunnel because I can't maintain the connection for any extended period of time.

Thoughts?  Solutions?

**Comment by mrfelton** [comment]
Also have this problem

**Comment by MaksRamenskiy** [comment]
Also have this problem. Do you know how fix this?

**Comment by mrfelton** [comment]
Use https://ngrok.com/ !

**Comment by dpkonofa** [comment]
ngrok is great, but I'm not paying $5/month just to get custom subdomains.

**Comment by defunctzombie** [comment]
It happens when the localtunnel server crashes and restarts. Your previous connection is lost. The error message is not super helpful because it makes it seem like a connection couldn't be established in the first place.

**Comment by dpkonofa** [comment]
So how do we get insight into *why* it's crashing and can we have a fallback where, if it does crash, it restarts the server with the same params passed the last time it was run?

**Comment by michaelgilley** [comment]
:+1:

**Comment by zoic21** [comment]
Hi,
I got the sam issue but tunnel seem to not restart alone, are they anyway to force rester after that ?

**Comment by devill** [comment]
I have the same issue, but also sometimes it crashes for quite a while. I get 504 Gateway Time-out.

**Comment by michaelgilley** [comment]
When I listen for the error on tunnel_cluster it allows localtunnel to attempt a reconnect. However, I noticed it does this several times in a row and then never successfully connects. @defunctzombie  Any ideas what might be causing the remote error and keeping from a reconnect to the server?

How might this issue be tested for resolution?

**Comment by clarkritchie** [comment]
This happens a lot for me as well.

**Comment by shreyakupadhyay** [comment]
I was also getting
Error: connection refused: localtunnel.me:undefined (check your firewall settings)

Using ngrok helped me it worked perfectly fine.

**Comment by skypy** [comment]
I have the same problem. Now using ngrok and it works perfectly.

**Comment by 99Percent** [comment]
Unfortunately I Had to give up on localtunnel and use ngrok because of this issue.

**Comment by puneetkaura** [comment]
On the verge of Giving up on Localtunnel and using ngrok ... huh

**Comment by defunctzombie** [comment]
Folks. I know local tunnel is crashing periodically. I don't have the time
right now to dig into it but if someone wants to look into the server side
the code is available.

**Comment by VLmja** [comment]
Using localtunnel.me for dev has been great!!!  With Node you should have a way to handle an error and restart because you need that anyway.  Use one of the many ways to auto restart your Node server and then on error just exit and let it restart for you. Node restarts blazing fast.  

tunnel.on('close', function () {
      process.exit(1);     
});

 tunnel.on('error', function (err) {
    process.exit(err);   
});

process.on('uncaughtException', function (er) {
 process.exit(err);   
});

Set an interval and ping yourself and if you get an error response, yeah, process.exit!

**Comment by vishaltelangre** [comment]
I love localtunnel. But this issue is a real bummer. 

Anybody working on this?

**Comment by vishaltelangre** [comment]
Cannot we simply retry something as follows here instead - https://github.com/localtunnel/localtunnel/blob/9a1d48764a167ae9fb05f42efdd7de0005e9edfc/lib/TunnelCluster.js#L43-L51

```js
remote.on('error', function(err) {
  if (err.code === 'ECONNREFUSED') {
    self.emit('error', new Error('connection refused: ' + remote_host + ':' + remote_port + ' (check your firewall settings)'));

    setTimeout(function() {
      remote.close();
      remote.listen(remote_port, remote_host);
    }, 1000);
  }
});
```

cc: @defunctzombie

**Comment by michaelkeenan** [comment]
I use a script that restarts localtunnel when it crashes:

`# localtunnel.me is useful, but crashes a lot. This script restarts it when it crashes.

require 'optparse'

options = {:subdomain => 'maenad', :port => 5000}

parser = OptionParser.new do|opts|
	opts.banner = "Usage: localtunnel.rb [options]"
	opts.on('-s', '--subdomain subdomain', 'Subdomain') do |name|
		options[:subdomain] = subdomain;
	end

	opts.on('-p', '--port port', 'Port') do |age|
		options[:port] = port;
	end

	opts.on('-h', '--help', 'Displays Help') do
		puts opts
		exit
	end
end

parser.parse!

def ordinal(number)
  abs_number = number.to_i.abs

  if (11..13).include?(abs_number % 100)
    "th"
  else
    case abs_number % 10
      when 1; "st"
      when 2; "nd"
      when 3; "rd"
      else    "th"
    end
  end
end

def ordinalize(number)
  "#{number}#{ordinal(number)}"
end

launch_count = 0

while true
	launch_count += 1
	puts "Running localtunnel for the #{ordinalize(launch_count)} time"
	`lt --port #{options[:port]} --subdomain #{options[:subdomain]}`
end`

**Comment by michaelkeenan** [comment]
I use a script that restarts localtunnel when it crashes:

```ruby
require 'optparse'

options = {:subdomain => 'defaultdomain', :port => 3000}

parser = OptionParser.new do|opts|
	opts.banner = "Usage: localtunnel.rb [options]"
	opts.on('-s', '--subdomain subdomain', 'Subdomain') do |name|
		options[:subdomain] = subdomain;
	end

	opts.on('-p', '--port port', 'Port') do |age|
		options[:port] = port;
	end

	opts.on('-h', '--help', 'Displays Help') do
		puts opts
		exit
	end
end

parser.parse!

def ordinal(number)
  abs_number = number.to_i.abs

  if (11..13).include?(abs_number % 100)
    "th"
  else
    case abs_number % 10
      when 1; "st"
      when 2; "nd"
      when 3; "rd"
      else    "th"
    end
  end
end

def ordinalize(number)
  "#{number}#{ordinal(number)}"
end

launch_count = 0

while true
	launch_count += 1
	puts "Running localtunnel for the #{ordinalize(launch_count)} time"
	`lt --port #{options[:port]} --subdomain #{options[:subdomain]}`
end
```

I've been running this for a couple of days, and it's restarted it 218 times. There must be occasional disruptions, but I haven't noticed them.

**Comment by JemarJones** [comment]
@michaelkeenan Does it restart at the same address, or do we get a different subdomain?

**Comment by michaelkeenan** [comment]
It restarts with the same address. The crucial line is this:

```ruby
`lt --port #{options[:port]} --subdomain #{options[:subdomain]}`
```

As you can see, it uses the port and the subdomain that are provided in the arguments to the script. So if you save the script as `localtunnel.rb`, you could run it like this:

`ruby localtunnel.rb --port 3000 --subdomain yourdomainhere`

That would keep running and restarting a localtunnel command with the port being 3000, and the URL being yourdomainhere.localtunnel.me

**Comment by Dave84c** [comment]
Hey Michael, I think there is an error in the Code.

`opts.on('-s', '--subdomain subdomain', 'Subdomain') do |name|
        options[:subdomain] = subdomain;
    end

    opts.on('-p', '--port port', 'Port') do |age|
        options[:port] = port;
    end`

shouldnt the block parameters match the option: name => subdomain, age =>port ?

Cheers,
Dave

**Comment by michaelkeenan** [comment]
Oops! You're right; I'd copied in an older version of my script, before I'd fixed that. Thanks!

**Comment by calidion** [comment]
seems very easy to get crashed?

**Comment by HasanY1989** [comment]
No solution to this?

**Comment by jhiesey** [comment]
Bump. This is still making my tests for (stream-http)[https://travis-ci.org/jhiesey/stream-http] unreliable. I'll have to look into something else if there isn't a solution.

**Comment by Laksa19** [comment]
i try this and work well

![a](https://cloud.githubusercontent.com/assets/16347475/19071994/11bd8bbc-8a5d-11e6-89bf-cf52554f62d9.PNG)
![b](https://cloud.githubusercontent.com/assets/16347475/19072000/1784d488-8a5d-11e6-8863-bd32371199b4.PNG)
![c](https://cloud.githubusercontent.com/assets/16347475/19072003/1b517238-8a5d-11e6-908b-17b9d2cf2eea.PNG)

**Comment by felipemarques** [comment]
You try use lt with supervisor ?

**Comment by fuzzy76** [comment]
Is this related to #106, or is that a totally different issue?

**Comment by willydk** [comment]
recommend to do sleep(60) in the while loop.

**Comment by rafay29** [comment]
Hey @willydk ,

did you try to use sleep in while? Does the solution work for you?

**Comment by willydk** [comment]
yea, I did sleep(60) within the while loop. Because the script detected the error before restarting the same subdomain, causing 504 gateway error after restart. i added sleep(60), and has been restarted 23 times in 24 hours, no more gateway error. 30 seconds would probably work too. But i don't really care it goes down for 1-2 minutes

**Comment by JerryGreen** [comment]
The issue is still present.

Ngrok does not have bugs like this but I like localtunnel for ability for choosing domain which is a paid feature in ngrok.

**Comment by wayne5w** [comment]
Same problem here. Given this has been open for more than a year I guess switching to ngrok is warranted.

**Comment by Alderon86** [comment]
the script worked fine but after a crash its not starting anymore.
Its only saying Starting for the 1st time and then nothing more happens
whats wrong?

**Comment by Hacker432-Y550** [comment]
A simple bash script to restart it every time it crashes

#!/bin/bash

function localtunnel {
        lt -s subdomain --port port_number
}

until localtunnel; do
        echo "localtunnel server crashed"
        sleep 2
done

**Comment by defunctzombie** [comment]
Closing this issue. I am aware of some stability issues and am trying some things to improve them. Hopefully the hacks people have suggested (or alternative projects) have helped those that struggle the most with localtunnel stability issues.

This is a side project for me so I am not able to address all of the concerns but am trying to make it more stable.

**Comment by dreki** [comment]
I vote for leaving this issue open until it's fixed. Closing it makes it seem like localtunnel is more stable than it is. People end up frustrated as a result.

**Comment by JerryGreen** [comment]
+1 for @dreki 

This is fair to have this issue opened while it's not fixed

**Comment by michaelkeenan** [comment]
When I have trouble getting something to work, I often go to the Issues tab to see whether it's a known problem, and it often helps. But if this issue is marked closed, it'll be invisible on the default filter of the Issues tab. So I think dreki is right - leaving the issue open is better, even if it'll never be fixed. localtunnel is still useful (btw thank you for making it! :) ) even if it's unstable, but it's more useful when people can see this thread and see the workarounds suggested in it.

**Comment by dreki** [comment]
Thank you both for weighing in! Im happy I'm not alone. 

@michaelkeenan that's a great point. That's how I work too. 

localtunnel is still great. I just use @Hacker432-Y550 's script. Keep up the good work, @defunctzombie. None of us would be here without you.

**Comment by vishaltelangre** [comment]
Exactly. Please keep this issue opened even if there is no correct solution.

**Comment by Ryccoo** [comment]
I am not able to start it, it is not occasional for me. Every launch ends up with

usr/local/lib/node_modules/localtunnel/bin/client:58
        throw err;
              ^
Error: connection refused: localtunnel.me:42075 (check your firewall settings)
    at Socket.<anonymous> (/usr/local/lib/node_modules/localtunnel/lib/TunnelCluster.js:47:32)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)


Are there some updates on this issue ?

**Comment by Capriatto** [comment]
+1 for @dreki. Keep this issue open.

**Comment by defunctzombie** [comment]
There is already another issue talking about the same thing. Don't need two of them. I know this happens :)
